Asp.Net_Core_Portfolio/Controllers/SkillController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Asp.Net_Core_Portfolio.Controllers
{
    public class SkillController : Controller
    {
        SkillManager skillManager = new SkillManager(new EfSkillDal());
        public IActionResult Index()

        {

            var values=skillManager.GetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddSkill() 
        {

        return View();  
        }
        [HttpPost]
        public IActionResult AddSkill(Skill p)
        {
            skillManager.TAdd(p);

            return RedirectToAction("Index");
        }
        public IActionResult DeleteSkill(int id)
        {
            var values=skillManager.TGetById(id);
            skillManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditSkill(int id)
        {

            var values = skillManager.TGetById(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditSkill(Skill p)
        {
            skillManager.TUpdate(p);
            return RedirectToAction("Index");
        }
    }
}

Asp.Net_Core_Portfolio/Views/Skill/AddSkill.cshtml
@{
    ViewData["Title"] = "AddSkill";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}
@using (Html.BeginForm("AddSkill", "Skill", FormMethod.Post))
{

    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Add Skill!</h4>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" class="form-control" name="SkillTitle">
                    </div>
                    <div class="form-group">
                        <label>Date</label>
                        <input type="text" class="form-control" name="SkillValue">
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Add</button>
                    <button class="btn btn-dark">Cancel</button>
                </form>
            </div>
        </div>
    </div>
}

Asp.Net_Core_Portfolio/Views/Skill/EditSkill.cshtml
@model EntityLayer.Concrete.Skill
@{
    ViewData["Title"] = "EditSkill";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

@using (Html.BeginForm("EditSkill","Skill",FormMethod.Post)){

    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Edit Skill!</h4>
                <form class="forms-sample">
                    <div class="form-group">
                        @Html.HiddenFor(x => x.SkillID, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Title</label>
                        @Html.TextBoxFor(x => x.SkillTitle, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Date</label>
                        @Html.TextBoxFor(x => x.SkillValue, new { @class = "form-control" })
                    </div>                 
                    <button type="submit" class="btn btn-primary mr-2">Save</button>
                    <button class="btn btn-dark">Cancel</button>
                </form>
            </div>
        </div>
    </div>
}

Asp.Net_Core_Portfolio/Views/Skill/Index.cshtml
@using EntityLayer.Concrete
@model List<Skill>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}
<div class="card-header bg-transparent border-0">
    <h3 class="text-white mb-0">My Skills </h3>
</div>
<div class="table-responsive">
    <br />
    <a href="/Skill/AddSkill" class="btn btn-outline-dark">Add Skill</a>
    <br />
    <table class="table align-items-center table-dark table-flush">
        <thead class="thead-dark">
            <tr>
                <th scope="col" class="sort" data-sort="name">#</th>
                <th scope="col" class="sort" data-sort="budget">Title</th>
                <th scope="col" class="sort" data-sort="status">Ratio</th>
                <th scope="col">Edit</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody class="list">
                @foreach (var item in Model)
                {
            <tr>
                <td>
                    @item.SkillID
                </td>
                <td class="budget">
                    @item.SkillTitle
                </td>
                <td>
                    <div class="d-flex align-items-center">
                        <span class="completion mr-2">@item.SkillValue%</span>
                        <div>
                            <div class="progress">
                                    <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="@item.SkillValue" aria-valuemin="0" aria-valuemax="100" style="width: @item.SkillValue%;"></div>
                            </div>
                        </div>
                    </div>
                </td> 
                <td>
                        <a href="/Skill/DeleteSkill/@item.SkillID" class="btn btn-outline-danger">Delete</a>
                        <a href="/Skill/EditSkill/@item.SkillID" class="btn btn-outline-light">Update</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>


<script src="/Admin/assets/vendors/js/vendor.bundle.base.js"></script>