Asp.Net_Core_Portfolio/Controllers/PortfolioController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace Asp.Net_Core_Portfolio.Controllers
{
    public class PortfolioController : Controller
    {
        PortfolioManager portfolioManager=new PortfolioManager(new EfPortfolioDal());
        public IActionResult Index()
        {

            var values=portfolioManager.GetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddProject()
        {

            return View();
        }
        [HttpPost]
        public IActionResult AddProject(Portfolio p)
        {
            PortfolioValidator validations = new PortfolioValidator(); 
            ValidationResult result = validations.Validate(p);
            if (result.IsValid) {
                portfolioManager.TAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }

            }
            return View();
        }
        public IActionResult DeleteProject(int id)
        {
            var values = portfolioManager.TGetById(id);
            portfolioManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditProject(int id)
        {

            var values = portfolioManager.TGetById(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditProject(Portfolio p)
        {
            PortfolioValidator validations = new PortfolioValidator();
            ValidationResult result = validations.Validate(p);
            if (result.IsValid)
            {
                portfolioManager.TUpdate(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }

            }
            return View();

        }

    }
}

Asp.Net_Core_Portfolio/Views/Portfolio/AddProject.cshtml
@model EntityLayer.Concrete.Portfolio
@{
    ViewData["Title"] = "AddProject";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<div class="card-header border-0">
    <h3 class="mb-0">Add Projects Page</h3>
</div>
<br />
<br />
<br />

@using (Html.BeginForm("AddProject", "Portfolio", FormMethod.Post))
{

    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Add New Project Panel </p>
                <form class="forms-sample">
                    <br />
                    @Html.Label("Project Title")
                    @Html.TextBoxFor(x => x.PortfolioName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PortfolioName)
                    <br />
                    <label>Image 1</label>
                    @Html.TextBoxFor(x => x.PortfolioImageUrl, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PortfolioImageUrl)
                    <br />
                    <label>Image 2</label>
                    @Html.TextBoxFor(x => x.PortfolioImageUrl2, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PortfolioImageUrl2)
                    <br />
                    <label>Project URL</label>
                    @Html.TextBoxFor(x => x.PortfolioProjectUrl, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PortfolioProjectUrl)
                    <br />
                    <label>Price</label>
                    @Html.TextBoxFor(x => x.PortfolioFee, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PortfolioFee)
                    <br />
                    <label>Status</label>
                    @Html.TextBoxFor(x => x.PortfolioStatus, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PortfolioStatus)
                    <br />
                    <label>Platform</label>
                    @Html.TextBoxFor(x => x.PortfolioPlatform, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PortfolioPlatform)
                    <br />
                    <button class="btn btn-info">Save</button>
                </form>
            </div>
        </div>
    </div>

}

Asp.Net_Core_Portfolio/Views/Portfolio/EditProject.cshtml
@model EntityLayer.Concrete.Portfolio
@{
    ViewData["Title"] = "EditProject";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}


<div class="card-header border-0">
    <h3 class="mb-0">Edit Projects Page</h3>
</div>
<br />
<br />
<br />

@using (Html.BeginForm("EditProject", "Portfolio", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Portfolio Edit Panel </p>
                <form class="forms-sample">
                    @Html.HiddenFor(x => x.PortfolioID)
                    <br />
                    <br />
                    @Html.Label("Portfolio Title")
                    @Html.TextBoxFor(x => x.PortfolioName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PortfolioName)
                    <br />
                    <label>Image 1</label>
                    @Html.TextBoxFor(x => x.PortfolioImageUrl, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PortfolioImageUrl)
                    <br />
                    <label>Image 1</label>
                    @Html.TextBoxFor(x => x.PortfolioImageUrl2, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PortfolioImageUrl2)
                    <br />
                    <label>Project URL</label>
                    @Html.TextBoxFor(x => x.PortfolioProjectUrl, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PortfolioProjectUrl)
                    <br />
                    <label>Price</label>
                    @Html.TextBoxFor(x => x.PortfolioFee, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PortfolioFee)
                    <br />
                    <label>Status</label>
                    @Html.TextBoxFor(x => x.PortfolioStatus, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PortfolioStatus)
                    <br />
                    <label>Project URL</label>
                    @Html.TextBoxFor(x => x.PortfolioProjectUrl, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PortfolioProjectUrl)
                    <br />
                    <label>Platform</label>
                    @Html.TextBoxFor(x => x.PortfolioPlatform, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PortfolioPlatform)
                    <br />
                    <button class="btn btn-info">Save</button>
                </form>
            </div>
        </div>
    </div>

}

Asp.Net_Core_Portfolio/Views/Portfolio/Index.cshtml
@using EntityLayer.Concrete
@model List<Portfolio>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}               
<div class="row">
    <div class="col">
        <div class="card bg-default shadow">
            <div class="card-header bg-transparent border-0">
                <h3 class="text-white mb-0">My Projects</h3>
            </div>
            <div class="table-responsive">
                <table class="table align-items-center table-dark table-flush">
                    <thead class="thead-dark">
                        <tr>
                            @*<th scope="col" class="sort" data-sort="name">Platform</th>*@
                            <th scope="col" class="sort" data-sort="name">Project</th>
                            <th scope="col" class="sort" data-sort="budget">Budget</th>
                            <th scope="col" class="sort" data-sort="status">Status</th>
                            <th scope="col">Images</th>
                            <th scope="col" class="sort" data-sort="completion">Completion</th>
                            <th scope="col">Delete</th>
                            <th scope="col">Edit</th>
                        </tr>
                    </thead>
                    <tbody class="list">
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th scope="row">
                                    <div class="media align-items-center">
                                        <a href="#" class="avatar rounded-circle mr-3">
                                            <img alt="Image placeholder" src="@item.PortfolioPlatform">
                                        </a>
                                        <div class="media-body">
                                            <span class="name mb-0 text-sm">@item.PortfolioName</span>
                                        </div>
                                    </div>
                                </th>
                                <td class="budget">
                                    @item.PortfolioFee USD
                                </td>
                                <td>
                                    <span class="badge badge-dot mr-4">
                                        <i class="bg-success"></i>
                                        <span class="status">completed</span>
                                    </span>
                                </td>
                                <td>
                                    <div class="avatar-group">
                                        <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="Ryan Tompson">
                                            <img alt="Image placeholder" src="~/Template/images/team/emp-1.jpg">
                                        </a>
                                        <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="Romina Hadid">
                                            <img alt="Image placeholder" src="~/Template/images/team/emp-2.jpg">
                                        </a>
                                        <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="Alexander Smith">
                                            <img alt="Image placeholder" src="~/Template/images/team/emp-3.jpg">
                                        </a>
                                        <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="Jessica Doe">
                                            <img alt="Image placeholder" src="~/Template/images/team/emp-4.jpg">
                                        </a>
                                    </div>
                                </td>
                                <td>
                                    <div class="d-flex align-items-center">
                                        <span class="completion mr-2">@item.PortfolioStatus%</span>
                                        <div>
                                            <div class="progress">
                                                <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="@item.PortfolioStatus" aria-valuemin="0" aria-valuemax="100" style="width: @item.PortfolioStatus%;"></div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <a href="/Portfolio/DeleteProject/@item.PortfolioID" class="btn btn-outline-danger delete-btn">Delete</a>
                                </td>
                                <td>
                                    <a href="/Portfolio/EditProject/@item.PortfolioID" class="btn btn-outline-warning">Edit</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<br />
<a href="/Portfolio/AddProject/" class="btn btn-primary">New Project</a>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        document.querySelectorAll('.delete-btn').forEach(button => {
            button.addEventListener('click', function (event) {
                if (!confirm('Gerçekten silmek istiyor musunuz?')) {
                    event.preventDefault();
                }
            });
        });
    });
</script>